### ISSUE TITLE
Visualize Road

### ISSUE THREAD

**Issue by ChristianBirchler** [ChristianBirchler/sdc-scissor#58]
# User Story
As a user, I want to see visually the generated road so that I have a more comprehensive view on the test scenario.

# Acceptance Criteria
## Scenario 1: 
* Given: Test is generated
* When: Dedicated visualization command is entered
* Then: It saves an image of an abstract road

## Scenario 2:
* Given: Test is generated
* When: Dedicated visualization command is entered with option flag for actual trajectory
* Then: It saves an image of an abstract road with the actual trajectory line of the car run in the simulator

# Definition of Done
* Code is reviewed
* Code is manually tested in dev and test environments
* All code is integrated frequently
* Integration testing is performed
* SonarQube check is run to determine the code metrics
* Refactoring is done

# Tasks
- [ ] Identify library for visualization
- [ ] Plot the road lines
- [ ] Plot the trajectory
- [ ] Creat API/CLI
