### ISSUE TITLE
Adapt to realease-based project management

### ISSUE THREAD

**Issue by ChristianBirchler** [ChristianBirchler/sdc-scissor#59]
# User Story
As the repository owner, I want to prioritize issues according to release dates so that it is clear in what order issues need to be addressed to make the deadlines in time.

![IMG_1505](https://user-images.githubusercontent.com/33133633/177826742-38ab64e5-de17-4582-bce1-d369e78c3d2d.jpeg)

# Acceptance Criteria
## Scenario 1: 
* Given: Backlog with issues
* When: Release dates are known
* Then: Issues are prioritized

# Definition of Done
* Code is reviewed
* Code is manually tested in dev and test environments
* All code is integrated frequently
* Integration testing is performed
* SonarQube check is run to determine the code metrics
* Refactoring is done

# Tasks
- [x] Recall Marcela's suggestions (picture)
- [x] Get familiar with GitHub milestone
- [x] Create an additional layer for releases on the project board
