### ISSUE TITLE
Validate generated roads

### ISSUE THREAD

**Issue by ChristianBirchler** [ChristianBirchler/sdc-scissor#73]
# User Story
As a user, I want to generate roads that do not intersect with themselves or have too sharp turns.

# Acceptance Criteria
## Scenario 1: 
* Given: Generated road
* When: Simulation starts
* Then: The road is a single piece that does not intersect with itself.

## Scenario 2:
* Given: Generated road
* When: Simulation starts
* Then: The road is a single piece that does not have too sharp turns.

# Definition of Done
* Code is reviewed
* Code is manually tested in dev and test environments
* All code is integrated frequently
* Integration testing is performed
* SonarQube check is run to determine the code metrics
* Refactoring is done

# Tasks
- [x] Implement a intersection validator
- [x] Implement a sharp turn validator
- [x] Apply Decorator design pattern
- [x] Write tests
